### PR TITLE
fix: jenssegers mongodb eloquent model class does not exist

### LINKED ISSUE #245: jenssegers mongodb eloquent model class does not exist
- Laravel Version: 7.12.0
- PHP Version: 7.4
- Blueprint Version: dev-master
- Platform: Mac

### Description:
Class Jenssegers\Mongodb\Eloquent\Model does not exist
```
➜  testdummy git:(master) ✗ art blueprint:new
Created example draft.yaml

   ReflectionException

  Class Jenssegers\Mongodb\Eloquent\Model does not exist

  at vendor/laravel-shift/blueprint/src/Commands/TraceCommand.php:106
    102|             return null;
    103|         }
    104|
    105|         $reflectionClass = new \ReflectionClass($class);
  > 106|         if (!$reflectionClass->isSubclassOf(\Illuminate\Database\Eloquent\Model::class) || $reflectionClass->isSubclassOf('Jenssegers\Mongodb\Eloquent\Model')) {
    107|             return null;
    108|         }
    109|
    110|

      +28 vendor frames
  29  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
### Steps To Reproduce:

1. `laravel new testdummy --auth`
2. `cd ./testdummy`
3. `composer require laravel-shift/blueprint:dev-master  --dev`
4. `php artisan blueprint:new`

### draft.yaml:
```yaml
# N/A
```

### PR DESCRIPTION
**Pull request by nathane**
closes #245

### CODE REVIEW

File: src/Commands/TraceCommand.php [hunk 1]
```diff
@@ -98,16 +98,14 @@ private function appClasses()
 
     private function loadModel(string $class)
     {
-        if (!class_exists($class)) {
+        if (!class_exists($reflectionClass = new \ReflectionClass($class))) {
```
Comment (jasonmccreary) [inline src/Commands/TraceCommand.php:101]: Does this solve it? I thought `ReflectionClass` would throw an exception...

Comment (nathane) [reply src/Commands/TraceCommand.php]: no, it was just suppressing it.
