### PR TITLE
fix: invalid chaining of 'nullable' for 'foreignId'

### LINKED ISSUE #215: Invalid chaining of `nullable` for `foreignId`
- Laravel Version: 7.0.0
- PHP Version: 7.4
- Blueprint Version: 1.11.0
- Platform: Mac

### Description:
This is a bug pulled from [#213](https://github.com/laravel-shift/blueprint/issues/213#issuecomment-630075982) regarding the order of `nullable`.

In Laravel 7.0, it needs to immediately follow the `foreignId`, otherwise it will generate an error.

### Steps To Reproduce:
Here is an example draft file which should yield a migration with the invalid chaining.

```yaml
models:
  Cart:
    name: string
    user_id: id foreign nullable
```

### PR DESCRIPTION
**Pull request by Pr3d4dor**
This pull request fixes the invalid chaining of 'nullable' for 'foreignId'.

---
Closes #215

### CODE REVIEW

File: src/Generators/MigrationGenerator.php [hunk 1]
```diff
@@ -198,8 +207,13 @@ protected function buildPivotTableDefinition(array $segments)
         return trim($definition);
     }
 
-    protected function buildForeignKey(string $column_name, ?string $on, string $type, array $attributes = [])
-    {
+    protected function buildForeignKey(
```
Comment (jasonmccreary) [inline src/Generators/MigrationGenerator.php:210]: Please keep these one line.

File: tests/fixtures/migrations/nullable-chaining-laravel6.php [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+     * Run the migrations.
+     *
+     * @return void
+     */
+    public function up()
+    {
+        Schema::create('carts', function (Blueprint $table) {
+            $table->bigIncrements('id');
+            $table->string('name');
+            $table->unsignedBigInteger('user_id');
```
Comment (jasonmccreary) [inline tests/fixtures/migrations/nullable-chaining-laravel6.php:19]: Shouldn't this be `$table->unsignedBigInteger('user_id')->nullable();`...

**Comment by Pr3d4dor** [comment]
@jasonmccreary I've updated the pull request with requested changes.
