### PR TITLE
Fix pivot table migration and added custom traits, extended class and interfaces

### LINKED ISSUE #763: Wrong migration generated
- Laravel Version: 12.39.0
- PHP Version: 8.4.14
- Blueprint Version: 2.12.0
- Platform: Windows 

### Issue:
I Got a wrong migration from a supposed correct draft.yaml
while the migration for table nazione is correct, the one for table regione is not:

Schema::create('regione', function (Blueprint $table) { 
	$table->id(); 
	$table->string('codice', 3); 
	$table->string('descrizione', 100); 
	$table->string('codice_nazione', 2); 
	**$table->foreignId('id_nazione')->constrained('naziones', 'nazione');** 
	$table->string('ripart_geografica', 100)->nullable(); 
	$table->unique(['id_nazione', 'codice']); 
	$table->timestamps(); 
}); 

### draft.yaml:
```yaml
models:
    Nazione:
        meta:
            table: nazione
        codice: string:2 unique
        descrizione: string:100
        codice_iso: string:2 unique
        codice_istat: string:3 unique
        prefisso: string:5 nullable
        relationships:
            hasMany: Regione

    Regione:
        meta:
            table: regione
        codice: string:3
        descrizione: string:100
        codice_nazione: string:2
        id_nazione: foreign:nazione
        ripart_geografica: string:100 nullable
        indexes:
            - unique: id_nazione, codice
        relationships:
            belongsTo: Nazione

```

### PR DESCRIPTION
**Pull request by LorenzoPapi**
Actually fixes #763, along with a "correct" and a "wrong" migration creation test.

Also adds custom extended class, custom traits and custom interfaces for Models.

I'll also add these to Controller if the pr is reviewed as good.

### CODE REVIEW

**Comment by jasonmccreary** [comment]
@LorenzoPapi, thanks. Please fix the styling issue by running `vendor/bin/pint`. Also provide clarification on the PR comments.

In the future, please open separate PRs for separate features. I'm only willing to merge this as it has tests.

File: src/Models/Model.php [hunk 1]
```diff
@@ -261,4 +278,34 @@ public function polymorphicManyToManyTables(): array
     {
         return $this->polymorphicManyToManyTables;
     }
+
```
Comment (jasonmccreary) [inline src/Models/Model.php]: When you open a PR to add this for `Controller`, please extract all this into a trait. Maybe something like `ClassDefinition`.

File: tests/fixtures/drafts/model-with-custom-extended-class.yaml [hunk 2]
```diff
@@ -0,0 +1,6 @@
+models:
+  Car:
+    color: string
+
+    meta:
+      extends: App\Models\Base\Vehicle
```
Comment (jasonmccreary) [inline tests/fixtures/drafts/model-with-custom-extended-class.yaml]: Add the trailing new line.

File: composer.json [hunk 3]
```diff
@@ -18,6 +18,7 @@
         "symfony/yaml": ">=7.0"
     },
     "require-dev": {
+        "jasonmccreary/laravel-test-assertions": "^2.8",
```
[the remark this answers is not in the document]
Comment (LorenzoPapi) [reply composer.json]: I followed the README you posted.

> If you wish to run the tests generated by Blueprint, you should also install the [Additional Assertions](https://github.com/jasonmccreary/laravel-test-assertions) package:
> ```
> composer require --dev jasonmccreary/laravel-test-assertions
> ```

I can remove it if needed

[the remark this answers is not in the document]
Comment (jasonmccreary) [reply composer.json]: That installation is for a user of the package. This project is the source code for the package.

It's not needed. Please remove.

File: src/Models/Model.php (hunk 1 above)
Comment (LorenzoPapi) [reply src/Models/Model.php]: should I do it in this PR or should I wait for this merge first and then do another PR in which I put everything under a trait?

Comment (jasonmccreary) [reply src/Models/Model.php]: Yes, after this is merged you can refactor in the next PR.

**Comment by jasonmccreary** [comment]
@LorenzoPapi, tests are passing.

Please check the other draft files for trailing newlines. Then let me know if this is ready to merge.

**Comment by jasonmccreary** [comment]
@LorenzoPapi, alright. Thanks. Will merge shortly with a few cleanups.
