### PR TITLE
Remove superfluous `softDeletes` & `softDeletesTz` columns

### LINKED ISSUE #585: Need ignore softDeletesTz and softDeletes in resources and requests
- Laravel Version: 9.14
- PHP Version: 8.1
- Blueprint Version: 2.4
- Platform: Windows

### Issue:
In app/Http/Resources/PostResource.php:
```php
        return [
            'id' => $this->id,
            'title' => $this->title,
            'softdeletestz' => $this->softdeletestz,
        ];
```

In app/Http/Requests/PostStoreRequest.php:
```php
        return [
            'title' => ['required'],
            'softdeletestz' => ['required'],
        ];
```
### draft.yaml:
```yaml
Post:
    title: string:400
    softDeletesTz
```

### LINKED ISSUE #590: When using `softdeletes` a validation is added to the Request class
- Laravel Version: 9.38.0
- PHP Version: 8.1.12
- Blueprint Version: 2.4
- Platform: Mac

### Issue:

This leads to the error: 
> The softdeletes field is required.

```php
class ProjectStoreRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules(): array
    {
        return [
            'title' => ['required', 'string'],
            'softdeletes' => ['required'],
        ];
    }
}
```

### draft.yaml:
```yaml
models:
  Project:
    title: string
    softDeletes
```

### PR DESCRIPTION
**Pull request by ghostwriter**
Resolves #585 and closes #590

### CODE REVIEW

File: tests/Feature/Generators/MigrationGeneratorTest.php [hunk 1]
```diff
@@ -637,7 +637,7 @@ public function output_generates_constraint_for_uuid()
     /**
      * @test
      */
-    public function output_respects_softdelete_order()
+    public function output_softdelete_column_last()
```
Comment (jasonmccreary) [inline tests/Feature/Generators/MigrationGeneratorTest.php:640]: 🏄‍♂️
